apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccount: nginx
      containers:
      - name: app-migrate
        image: nginx:latest
        command: ["echo", "migrate"]
        envFrom:
          - secretRef:
              name: secretkv
