kind: Secret
apiVersion: v1
metadata:
  name: example-annotation
  annotations:
    avp.kubernetes.io/path: "secrets/data/nginx/config"
type: Opaque
stringData:
  username: <username>
  password: <password>
